version: '3.9'
services:
  base:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 26080302
      POSTGRES_USER: postgres
      POSTGRES_DB: store
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  server:
    image: store_app:v1.0.0
    depends_on:
      - base
    ports:
      - '8080:8080'
